# docker build -t grafana:10.0.3 .
# docker run -d --rm --name=grafana -e GF_SECURITY_ADMIN_USER=digitbrain -e GF_SECURITY_ADMIN_PASSWORD=digitbrain -p 3000:3000 grafana:10.0.3

FROM grafana/grafana:10.0.3

USER root
RUN mkdir -p /etc/grafana/certs
COPY ./certificates/server-cert.pem /etc/grafana/certs/server-cert.pem
COPY ./certificates/server-key.pem /etc/grafana/certs/server-key.pem
RUN chmod 600 /etc/grafana/certs/server-*
RUN chown grafana:root /etc/grafana/certs/*

RUN sed -i 's/;protocol = http/protocol = https/g' /etc/grafana/grafana.ini
RUN sed -i 's/;cert_file =/cert_file = \/etc\/grafana\/certs\/server-cert.pem/g' /etc/grafana/grafana.ini
RUN sed -i 's/;cert_key =/cert_key = \/etc\/grafana\/certs\/server-key.pem/g' /etc/grafana/grafana.ini
RUN sed -i 's/;admin_user = admin/admin_user = digitbrain/g' /etc/grafana/grafana.ini
RUN sed -i 's/;admin_password = admin/admin_password = digitbrain/g' /etc/grafana/grafana.ini